/* Generated By:JavaCC: Do not edit this line. REGConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface REGConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PR_PROGRAMA = 8;
  /** RegularExpression Id. */
  int PR_PUBLIC = 9;
  /** RegularExpression Id. */
  int PR_MAIN = 10;
  /** RegularExpression Id. */
  int PR_IF = 11;
  /** RegularExpression Id. */
  int PR_FOR = 12;
  /** RegularExpression Id. */
  int PR_WHILE = 13;
  /** RegularExpression Id. */
  int PR_ELSE = 14;
  /** RegularExpression Id. */
  int PR_PRINTLN = 15;
  /** RegularExpression Id. */
  int PR_READLN = 16;
  /** RegularExpression Id. */
  int PR_DO = 17;
  /** RegularExpression Id. */
  int PR_RETURN = 18;
  /** RegularExpression Id. */
  int PR_SWITCH = 19;
  /** RegularExpression Id. */
  int PR_CASE = 20;
  /** RegularExpression Id. */
  int PR_BREAK = 21;
  /** RegularExpression Id. */
  int DEL_PUNTO_COMA = 22;
  /** RegularExpression Id. */
  int DEL_LLAVE_ABRE = 23;
  /** RegularExpression Id. */
  int DEL_LLAVE_CIERRA = 24;
  /** RegularExpression Id. */
  int DEL_PARENTESIS_ABRE = 25;
  /** RegularExpression Id. */
  int DEL_PARENTESIS_CIERRA = 26;
  /** RegularExpression Id. */
  int DEL_COMA = 27;
  /** RegularExpression Id. */
  int DEL_DOSPUNTOS = 28;
  /** RegularExpression Id. */
  int DEL_GATO = 29;
  /** RegularExpression Id. */
  int DEL_QUE = 30;
  /** RegularExpression Id. */
  int DEL_QUEE = 31;
  /** RegularExpression Id. */
  int OP_ADD = 32;
  /** RegularExpression Id. */
  int OP_SUB = 33;
  /** RegularExpression Id. */
  int OP_MUL = 34;
  /** RegularExpression Id. */
  int OP_DIV = 35;
  /** RegularExpression Id. */
  int OP_MOD = 36;
  /** RegularExpression Id. */
  int OP_ASIG = 37;
  /** RegularExpression Id. */
  int OP_PESO = 38;
  /** RegularExpression Id. */
  int OP_POT = 39;
  /** RegularExpression Id. */
  int OP_MENOR = 40;
  /** RegularExpression Id. */
  int OP_MAYOR = 41;
  /** RegularExpression Id. */
  int OP_MENOR_IGUAL = 42;
  /** RegularExpression Id. */
  int OP_MAYOR_IGUAL = 43;
  /** RegularExpression Id. */
  int OP_IGUAL = 44;
  /** RegularExpression Id. */
  int OP_DIF = 45;
  /** RegularExpression Id. */
  int OP_AND = 46;
  /** RegularExpression Id. */
  int OP_OR = 47;
  /** RegularExpression Id. */
  int OP_NEG = 48;
  /** RegularExpression Id. */
  int OP_INC = 49;
  /** RegularExpression Id. */
  int OP_DEC = 50;
  /** RegularExpression Id. */
  int T_STRING = 51;
  /** RegularExpression Id. */
  int T_INT = 52;
  /** RegularExpression Id. */
  int T_FLOAT = 53;
  /** RegularExpression Id. */
  int T_BOOLEAN = 54;
  /** RegularExpression Id. */
  int VAL_STRING = 55;
  /** RegularExpression Id. */
  int VAL_INT = 56;
  /** RegularExpression Id. */
  int VAL_FLOAT = 57;
  /** RegularExpression Id. */
  int VAL_BOOLEAN = 58;
  /** RegularExpression Id. */
  int ID = 59;
  /** RegularExpression Id. */
  int NO_VALIDO = 60;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int DentroComentario2 = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"/*\"",
    "<token of kind 6>",
    "\"*/\"",
    "\"programa\"",
    "\"public\"",
    "\"main\"",
    "\"if\"",
    "\"for\"",
    "\"while\"",
    "\"else\"",
    "\"println\"",
    "\"readln\"",
    "\"do\"",
    "\"return\"",
    "\"switch\"",
    "\"case\"",
    "\"break\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\":\"",
    "\"#\"",
    "\"\\u00c2\\u00bf\"",
    "\"?\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"=\"",
    "\"$\"",
    "\"^\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"++\"",
    "\"--\"",
    "\"string\"",
    "\"int\"",
    "\"float\"",
    "\"boolean\"",
    "<VAL_STRING>",
    "<VAL_INT>",
    "<VAL_FLOAT>",
    "<VAL_BOOLEAN>",
    "<ID>",
    "<NO_VALIDO>",
  };

}
